# Generated by Django 5.1.2 on 2024-11-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_member_id_alter_ministry_id_alter_shepherd_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tithe',
        ),
    ]
